### ISSUE TITLE
I can't find Labyrinth Enchantment

### ISSUE THREAD

**Issue by igorcastroo** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#104]
I can't find Labyrinth Enchantment, in unique helms

![Sem título](https://user-images.githubusercontent.com/39240321/86481689-dea53f80-bd26-11ea-8f4d-eb85613da11f.png)

![Sem título2](https://user-images.githubusercontent.com/39240321/86481825-1ca26380-bd27-11ea-957d-34d07490619a.png)

**Comment by WhiteFang5** [comment]
Can you copy-paste the item in a new reply (please use a code-snipped to preserve formatting)

**Comment by WhiteFang5** [comment]
I've searched for the stat on the PoE trade website and it should be fixed in the next release:
![image](https://user-images.githubusercontent.com/4527188/87140092-3866b600-c2a1-11ea-9c9f-da602ddb7f4b.png)

**Comment by WhiteFang5** [comment]
This issue has been fixed in v0.7.3
