### ISSUE TITLE
Suggestion: Use bulk item (item exchange) for currencies / consumable instead of normal trade

### ISSUE THREAD

**Issue by Kyria** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#105]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**
When you price check currencies, fossils, cards, etc etc, you always have trades instead of item exchange. In some case it's fine, but when someone have like 30 stack of the same card, it displays 30times the same name instead of once like in item exchange 

Example (you can probably find other examples like this):
![image](https://user-images.githubusercontent.com/1838373/86511779-8b052580-bdfc-11ea-82f3-f2dbc25b672e.png)
![image](https://user-images.githubusercontent.com/1838373/86511798-b0922f00-bdfc-11ea-956f-8497cac21b3d.png)
/edit: I don't understand also why it's red with different results when I search it... :/

**Describe the solution / alternatives you'd like**
Either group names, use the item exchange, or if it's too complicated, allow us to filter out names (like the ignore in the trade site)

Thanks for your work ! :)

**Comment by WhiteFang5** [comment]
Bulk exchange has been implemented in v0.7.11
