### ISSUE TITLE
Suggestion: Allow rebinding of Stash tab navigation (CTRL+Scroll)

### ISSUE THREAD

**Issue by JustCallMeCharlie** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#109]
Problem: Many players like to rebind their scroll wheel to send click inputs while modifier keys are held (ToS compliant since it's only one action per input) , specifically in this case i want to be able to hold down control and scroll to move items in and out of stash. as of now, that means i have to disable the CTRL+Scroll stash navigation, one of my favorite features of overlay. 

Request: Allow the CTRL+scroll functionality to be set to another modifier key in the config

**Comment by wratho** [comment]
are you imaging just other modifier keys like alt & shift? of do you want to completely rebind it to non scroll as well?
