### ISSUE TITLE
Autoupdate not working

### ISSUE THREAD

**Issue by professorvandough** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#118]
On load app says update exists and will be downloaded unless otherwise specified.  Autoupdate is enabled, download never happens.

**Comment by AbeLincoln** [comment]
I can confirm the same bug.

**Comment by Irfy** [comment]
+1 Had to update to 0.7.2 manually. (And then chaos currency search stopped working but that's another issue)

**Comment by ruiwei777** [comment]
0.7.2 has fixed this bug and can be automatically update to 0.7.3 (you'll still need to manually relaunch)

**Comment by Zenzou** [comment]
auto update not working. I've had to manually download/install 7.4/7.5/7.6

**Comment by WhiteFang5** [comment]
Auto Update has been fixed since 0.7.11
