### ISSUE TITLE
QoL: Keep PoE focused when displaying overlay

### ISSUE THREAD

**Issue by Irfy** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#120]
Would it be possible to change the overlay window attributes so that PoE is kept in focus while showing the overlay window? It *should* be possible somehow: PoE-TradeMacro does it that way -- PoE is still in focus while a list of prices is shown.

If the user clicks on the overlay to perform further actions, then, obviously, PoE should lose focus, but not before that.

The benefits to this are two-fold:

1. By leaving PoE in focus, one can price check multiple items one after the other without first having to refocus PoE. Right now, we have to click on the PoE client just to bring PoE into focus, before doing another Ctrl-D.

2. The background FPS-limit is a *very* useful tool to prevent high CPU/GPU usage when PoE is in the background, but introduces a delay when switching back to PoE. This is perfectly fine for alt-tabbing and doing some work for a while, but very annoying when quickly price-checking multiple items. Each time the overlay is shown, PoE is slowed down and then has the mentioned delay when we refocus it to price-check the next item. Leaving PoE in focus would prevent this for all simple price-checks (as long as the overlay is not clicked).

Right now, PoE-TradeMacro has both of the benefits by leaving PoE in focus.

**Comment by Wibbbs** [comment]
This would be fantastic if possible. It would also solve the problem of the mute when in background issue. If you have mute when in background enabled it mutes everyone you bring up the overlay.

**Comment by RuanJacobz** [comment]
> This would be fantastic if possible. It would also solve the problem of the mute when in background issue. If you have mute when in background enabled it mutes everyone you bring up the overlay.

Hey, if you uncheck "Focusable" under Settings > App this problem is solved!

**Comment by Irfy** [comment]
Yup, unchecking fousable yields the desired behaviour. Only problem is, we then no longer can edit the values -- oh well can't both have the cake and eat it I guess :)
