### ISSUE TITLE
Voices Variable Mod is Incorrect 

### ISSUE THREAD

**Issue by livejamie** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#121]
![image](https://user-images.githubusercontent.com/49513/87991896-dcb7dc00-ca9b-11ea-84aa-a2907689cb0b.png)

Overlay is considering the top line with the 3 as the variable:
![image](https://user-images.githubusercontent.com/49513/87991934-f6592380-ca9b-11ea-8aa7-0058ad9f514d.png)

It's the bottom line which is a variable of 1-7, which can _massively_ influence the value of the item.

It's always 3 jewel sockets.

**Comment by WhiteFang5** [comment]
Can you please copy-paste the item wrapped in a code-section?

**Comment by livejamie** [comment]
```
Rarity: Unique
Voices
Large Cluster Jewel
--------
Item Level: 75
--------
Adds 3 Jewel Socket Passive Skills
Adds 5 Small Passive Skills which grant nothing
--------
Only a madman would ignore a god's instructions.
--------
Place into an allocated Large Jewel Socket on the Passive Skill Tree. Added passives do not interact with jewel radiuses. Right click to remove from the Socket.
--------
Corrupted
```

The first line of 3 passive skills always stays the same, the second line "small passive skills" can be 1, 3, 5 or 7.

**Comment by WhiteFang5** [comment]
When price-checking the copied jewel I get the following result:
![image](https://user-images.githubusercontent.com/4527188/88259172-110ce180-ccc2-11ea-8402-b6bfd22413b5.png)

This seems to be correct through.  
Even with the fact that the # of Jewel Sockets is always 3, and # of Small Passive skills can indeed range from 1~7.  
  
I do however see an issue with the first screenshot of the initial post:  
When the jewel adds exactly 1 small passive, you get a fixed line that doesn't allow you to change the number range (it's fixed to "1").  
This particular issue also occurs in many other items too, for example `Skills fire an additional Projectile` and `Skills fire # additional Projectiles` (and about 1371 other stats!)  
I'll look into a solution for all those stats.

**Comment by livejamie** [comment]
Ah that makes sense, sorry for the confusion.

**Comment by livejamie** [comment]
It wouldn't be an issue if the first screenshot example gave an accurate price.

**Comment by WhiteFang5** [comment]
> It wouldn't be an issue if the first screenshot example gave an accurate price.

That's where the latter part of my reply is about. It identifies the stat incorrectly and doesn't offer you an option to change the number range. Due to this, it evaluates the stat (incorrectly!) with a blanco value, or simply put, "any" number of added small passives.  
That's why I want to look into those stats and fix them accordingly so it'll look them up with a value of "1" instead of "any" and allows you to change the number range.
(I already have a draft fix available, so it might make it into a next release quite soon)

**Comment by livejamie** [comment]
That was quick thanks!
