### ISSUE TITLE
an error occurred while parsing the item 0.7.3

### ISSUE THREAD

**Issue by ruivaotft** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#130]
##🐞 bug report

When i try to see the value of any item i'm getting this error "an error occurred while parsing the item", it just started happening in this update.

## 🌍  Your Environment

- OS: Win10 x64
- Version: 0.7.3 
- PoE: Latest English

**Comment by WhiteFang5** [comment]
Can you copy-paste the item here (in a code section) please?

**Comment by adikavemen** [comment]
Hi @WhiteFang5 this issue is quite old and looks like it can be closed as it has been years since being posted.
