### ISSUE TITLE
Hotkeys don't work

### ISSUE THREAD

**Issue by interfector18** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#131]
# 🐞 bug report

**Describe the bug**
Keyboard hotkeys do not work.

**To Reproduce**
1. Open the app
2. Open the game
3. Press hotkeys

**Expected behavior**
Pressing F5, F6. Ctrl + D to make something happen.

## 🌍  Your Environment
- OS: Manjaro KDE
- Version:  0.7.3 AppImage
- PoE: Steam 3.11.1/c English

I'm speculating they don't get registered properly, there is no error message nor a normal message in the app log aside from 'app starting', 'checking updates'.

**Comment by versedi** [comment]
@interfector18 try to activate the overlay first by spamming "F7".
As soon as you see "POE Overlay x.x.x." in bottom left corner then try to use the shortcut.

**Comment by interfector18** [comment]
@versedi I've tried, nothing came up.

**Comment by rzyghul** [comment]
same issue here on manjaro xfce. Hitting F7 and other shortcuts does nothing, "POE Overlay x.x.x."  does not show up in bottom left corner of game but application itself in running, icon is present in tray and I can right click it and enter settings.

**Comment by rzyghul** [comment]
I'm out of ideas at this moment ;)

**Comment by interfector18** [comment]
I've tried `npm start` and it works for me too, didn't encounter the TypeError above though. Locally built and appimage didn't work for me either. Perhaps detection is the real issue.

**Comment by rzyghul** [comment]
I confirm this also has fixed issue for me. I had to install xorg-xwininfo as the other package was already installed at my end.

**Comment by binarydepth** [comment]
I confirm too that having both xorg-xprop and xorg-xwininfo solves the issue
