### ISSUE TITLE
Mod: 

### ISSUE THREAD

**Issue by versedi** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#133]
# 🛸 Item modifier report

**Current item modifier**
```
#% increased Experience gain (Maps)
```

**Expected item modifier**
```
#% increased Experience gain
```

**Copied item data**
```
Rarity: Unique
Perandus Signet
Paua Ring
--------
Item Level: 83
--------
+23 to maximum Mana (implicit)
--------
+28 to maximum Mana
50% increased Mana Regeneration Rate
2% increased Experience gain
2% increased Intelligence for each Unique Item Equipped
3% additional chance for Slain monsters to drop Scrolls of Wisdom
--------
"Our warehouses are bursting. Our vaults are full.
But our minds are still hungry."
- Medici Perandus, Prefect to the Treasury
```

**Screenshots**

![overlay](https://user-images.githubusercontent.com/7837369/88853380-ed7cf600-d1ef-11ea-8512-97b2d23d3ea8.png)
![pathofexiletrade](https://user-images.githubusercontent.com/7837369/88853390-f2da4080-d1ef-11ea-8848-1ae7d0eefebc.png)

## 🌍  Your Environment

- Version:  0.7.3 portable
- PoE: . standalone/English

**Comment by WhiteFang5** [comment]
This has been fixed in v0.7.4
