### ISSUE TITLE
"Seeker Runes" CJ Notable Breaks Evaluate

### ISSUE THREAD

**Issue by IdrisQe** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#136]
# 🐞 bug report

**Describe the bug**

Any cluster jewel with the mod "Seeker Runes" will not display any selectable modifiers in Evaluate, and the top will show "Seek" erroneously

**To Reproduce**
1. Have a cluster jewel (Medium, Brand Damage) with Seeker Runes.
2. Attempt to evaluate said Cluster Jewel.

**Expected behavior**
Mods show and are selectable in Evaluate window.

**Screenshots**
![image](https://user-images.githubusercontent.com/40530630/89721713-c82d7c00-d995-11ea-88b4-e3eb5a66f070.png)

## 🌍  Your Environment

- OS: Windows 10 x64
- Version: 0.7.3
- PoE: Steam, unsure exact version, probably irrelevant

**Comment by WhiteFang5** [comment]
Sample Item (that has this issue):
```
Rarity: Rare
Soul Splinter
Medium Cluster Jewel
--------
Requirements:
Level: 54
--------
Item Level: 74
--------
Adds 6 Passive Skills (enchant)
1 Added Passive Skill is a Jewel Socket (enchant)
Added Small Passive Skills grant: 12% increased Brand Damage (enchant)
--------
Added Small Passive Skills also grant: +24 to Armour
Added Small Passive Skills also grant: +4 to Dexterity
1 Added Passive Skill is Seeker Runes
--------
Place into an allocated Medium or Large Jewel Socket on the Passive Skill Tree. Added passives do not interact with jewel radiuses. Right click to remove from the Socket.
--------
Note: ~price 1 chaos
```

Dev notes: it seems odd that none of the stats show up. I would've expected atleast the armour & dex to show up, but they don't show either.
