### ISSUE TITLE
Mod: +Evasion Rating on Items without a base amount of evasion

### ISSUE THREAD

**Issue by Kryai** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#138]
This attempts to search for evasion rating (local) but it should not be a local search as quivers don't get evasion, this is a global modifier.
Wrong:
https://www.pathofexile.com/trade/search/Harvest/95EV6P0sK

Right:
https://www.pathofexile.com/trade/search/Harvest/WqB379mFm

**Comment by Kryai** [comment]
Item text:

Rarity: Unique
The Signal Fire
Fire Arrow Quiver
--------
Requirements:
Level: 24
--------
Item Level: 70
--------
Adds 4 to 8 Fire Damage to Bow Attacks (implicit)
--------
10% increased Attack Speed
+96 to Evasion Rating
+30 to maximum Mana
Gain 34% of Physical Damage as Extra Fire Damage
50% of Physical Damage Converted to Fire Damage
Adds 5 to 10 Fire Damage to Bow Attacks
--------
Fire spreads thick and fast.
The first spark is never the last.
--------

**Comment by Kryai** [comment]
same problem with amulets:

Rarity: Unique
The Ignomon
Gold Amulet
--------
Requirements:
Level: 8
--------
Item Level: 69
--------
13% increased Rarity of Items found (implicit)
--------
+10 to Dexterity
Adds 12 to 24 Fire Damage to Attacks
+117 to Accuracy Rating
+102 to Evasion Rating
+20% to Fire Resistance
--------
The light that reveals is the glare that blinds.

**Comment by WhiteFang5** [comment]
This issue is resolved in v0.7.4
