### ISSUE TITLE
Mod: #% increased Experience gain

### ISSUE THREAD

**Issue by Kryai** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#139]
There are two versions of this modifier. One present on certain unique maps, and another on unique items.

Searching Perandus Signet pulls up the wrong modifier.

https://www.pathofexile.com/trade/search/Harvest/k7ep5Qrs5

Rarity: Unique
Perandus Signet
Paua Ring
--------
Item Level: 82
--------
+24 to maximum Mana (implicit)
--------
+26 to maximum Mana
47% increased Mana Regeneration Rate
2% increased Experience gain
2% increased Intelligence for each Unique Item Equipped
3% additional chance for Slain monsters to drop Scrolls of Wisdom
--------
"Our warehouses are bursting. Our vaults are full.
But our minds are still hungry."
- Medici Perandus, Prefect to the Treasury

**Comment by WhiteFang5** [comment]
This'll be fixed in release 0.7.4
