### ISSUE TITLE
Says Update Available at Start - but Update isn't downloaded

### ISSUE THREAD

**Issue by Reithan** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#155]
# 🐞 bug report

**Describe the bug**
I keep getting the "Update Available, will be downloaded" prompt on startup, but whether I close or relaunch, it never seems to update. I've tried waiting several minutes, but there's also now way to see what the update progress might be?

## 🌍  Your Environment

- OS: Win10 x64
- Version: 0.7.3
- PoE: Steam

**Comment by AkumaNoTsubasa** [comment]
having this too for over 3 weeks now

**Comment by fatings** [comment]
same here from 0.7.4 to 0.7.5

**Comment by Noshei** [comment]
same issue here with 0.7.5 to either 0.7.6 or 0.7.7

**Comment by antarek** [comment]
Same issue here. So i removed the setup version and just use the portable one for the moment and ll update it by myself when a new version is released.

**Comment by Neltisen** [comment]
Same issue here. Auto update function do not work at all since back when I started using it (over half a year ago)

**Comment by WhiteFang5** [comment]
Auto update functionality should be fixed since 0.7.12 ; Multiple issues have been identified and corrected, which should allow auto updating to work properly once again.

**Comment by fatings** [comment]
Working now. Thanks.
