### ISSUE TITLE
When checking price on Chaos Orbs, the Exalt value is fixed and wrong

### ISSUE THREAD

**Issue by daxtep** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#171]
When checking the price on how much your Chaos Orbs are worth in Exalts, it always shows a value of 50 Chaos per Exalt since league start. It doesn't update.

**Comment by WhiteFang5** [comment]
I've looked into this issue and it appears to be that the item exchange rate service actually ceils the exchange rate to two digits after the decimal separator. This causes incorrect calculations to occur when a stack of chaos is evaluated.  
  
I've create a PR to move the rounding away from the exchange rate, to the view. Meaning that a stack would be calculated using the un-rounded exchange rate value, which is then rounded after the rate is multiplied with the stack amount, to be displayed.
