### ISSUE TITLE
Bubbling Flask mods can't find anything

### ISSUE THREAD

**Issue by scafutto20** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#175]
# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win7 x64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

This is not that deep to make a perfect report, the thing is, when I try to search for Bubbling Flasks mods it simply won't work like the other flask mods.

**Comment by WhiteFang5** [comment]
Thank you for reporting this issue. I've looked into it and submitted a fix for it. It'll be fixed in the next release.
