### ISSUE TITLE
Crafted Energy Shield generates incorrect search param

### ISSUE THREAD

**Issue by Razunter** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#176]
Item:
![overlay](https://user-images.githubusercontent.com/362900/106393057-42ebc700-640e-11eb-8597-4fffe6941e1f.png)

This ES mod is crafted and Overlay generates search with `# to maximum Energy Shield (Local)`, getting 0 results. It should be just `# to maximum Energy Shield` without `local`.

- OS: Windows 10 x64
- Version: 0.7.7
- PoE: Steam 3.13.1 English

**Comment by WhiteFang5** [comment]
Thank you for reporting this issue. I've looked into it and have submitted a fix that'll be applied in the next release.
