### ISSUE TITLE
Bug Poe Overlay 

### ISSUE THREAD

**Issue by DiegoFunghetto** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#181]
Oh hi there! 😄

I was using Poe Overlay when I came across the following error: "if this keeps happening please try lowering fetched item count".

I already restarted the PC, reinstalled Poe Overlay and the error continues, could someone help me with that?

- OS:  Win10 home x64
- Version:  0.7.7
- PoE: Steam 3.13 English

**Comment by WhiteFang5** [comment]
Probably you've hit the rate limit (amount of look-ups per minute). It usually takes about 15 minutes to reset and allow new look-ups. This limit is imposed by GGG, and there's nothing PoE Overlay can do about it once you've reached this limit.
