### ISSUE TITLE
Legion jewels generate wrong search param

### ISSUE THREAD

**Issue by Razunter** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#182]
Legion jewels (historic) generate `Commissioned # coins to commemorate Cadiro` every time on /trade site regardless of actual mod.

Item example:
```
Rarity: Unique
Glorious Vanity
Timeless Jewel
--------
Limited to: 1 Historic
Radius: Large
--------
Item Level: 82
--------
Bathed in the blood of 4234 sacrificed in the name of Ahuana
Passives in radius are Conquered by the Vaal
Historic
--------
They believed themselves the pinnacle of civilisation, but that height toppled their empire.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
```

Screenshots:
![Jewel](https://user-images.githubusercontent.com/362900/107102357-c1dc6780-6833-11eb-9f52-1e27f38faf4d.png)
![Search result](https://user-images.githubusercontent.com/362900/107102380-c86adf00-6833-11eb-9fca-0bdaa4515de6.png)

**Comment by WhiteFang5** [comment]
I've looked into this, and on the latest master (v0.7.14 + earlier fixes -- commit d147d0e) it appears to be working fine.  
I'll close this issue, since it seems solved. If it does break again in the next or a following release, feel free to re-open this issue or create a new one.
