### ISSUE TITLE
Decimal Point Missing 

### ISSUE THREAD

**Issue by Jivonchi** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#185]
# 🐞 bug report

**Describe the bug**
Decimal point missing from Critical Strike Chance and Attack Per Second values. 

**To Reproduce**
1. Evaluate item (Ctrl + D) 
2. See error

**Expected behavior**
Decimal point in Critical Strike Chance and Attack Per Second values. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41033861/108981641-e0fa4680-76c7-11eb-8e60-de082ee86421.png)

## 🌍  Your Environment

- OS: Win10 x64
- Version: 0.7.8 portable 
- PoE: Standalone 3.13

**Comment by WhiteFang5** [comment]
This issue has been fixed in v0.7.9
