### ISSUE TITLE
Problem Searching for Unique Flasks

### ISSUE THREAD

**Issue by FeralRage7** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#19]
###  🐞 
**Bug Report**

There is something wrong with how PoE Overlay searches **unique flasks**. From what I can see it grabs the implicits and the explicits and searches. As soon as you click off any implicits, the search completes and returns the correct results. 

Examples: 
Lion's Roar: returns no results with all mods selected. As soon as you unselect the +3000 armor (the implicit), the search results show properly. 
Forbidden Taste: no results with all mods selected. Unselect chance to dodge attack hits and chance to dodge spell hits, results show up as normal.

**To Reproduce**
Search any unique flask, the bug worked for all the ones I owned.

**Screenshots**
Broken
![roar broken](https://user-images.githubusercontent.com/61394919/84535460-b3d44800-aca0-11ea-8eb7-8c3865ca2c38.png)
Working (after de-selecting the implicit)
![roar working](https://user-images.githubusercontent.com/61394919/84535540-d7978e00-aca0-11ea-9e8c-d98be5e7075f.png)

###  🌍  
Your Environment

- OS: Win10 Pro
- Version:  0.6.28
- PoE:  Steam 3.10.2/c English

**Comment by WhiteFang5** [comment]
I've checked with the same version, and I don't see this happening at all:
![image](https://user-images.githubusercontent.com/4527188/84565083-05470a80-ad67-11ea-8fc5-7754e695c5e3.png)

**Comment by WhiteFang5** [comment]
I've looked into Forbidden Taste, and it does have the implicit issue (implicits being selected for the search):
![image](https://user-images.githubusercontent.com/4527188/84570916-92528980-ad90-11ea-8b2d-394859de9989.png)
