### ISSUE TITLE
"+# to Armour" on belts searches "+# to Armour (Local)" resulting in no results

### ISSUE THREAD

**Issue by Alialun** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#193]
**Bug Description:**
When you click on "+# to Armour" on belt to search with it it actually adds "+# to Armour (Local)" to the search querry which doesn't exist on belts and results always in "No Results Found"

**Expected Behavoir:**
"+# to Armour" exists as separate search option on tradesite so PoE Overlay should add that with belts.

EDIT: It appears to be problem with every jewellry

**Comment by WhiteFang5** [comment]
I've looked into this issue and found that a number of "local" vs "global" stats were incorrect. I've fixed them all, even added some missings ones too. This fix will be shipped with the next release.
(Fix commit: d147d0e)
