### ISSUE TITLE
Evaluating Unique Items causes an Error

### ISSUE THREAD

**Issue by AbeLincoln** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#194]
# 🐞 bug report

**Describe the bug**
Attempting to evaluate a unique item will cause an error.

**To Reproduce**
1. Identify a unique item.  (I have not tried on unidentified uniques yet - all 15 or so I have tried reproduce this error)
2. Use the hotkey for evaluation (Ctrl+D)
3. See message "An error occurred while parsing the item"

**Expected behavior**
A regular window with price prediction will appear.

## 🌍  Your Environment

- OS: Win 10 x64
- Version: 0.7.11
- PoE: Standalone 3.14.0/b English

**Comment by AbeLincoln** [comment]
This is the image of the message that I see:
![image](https://user-images.githubusercontent.com/16183837/115566658-71987180-a288-11eb-9638-b7c647d671ee.png)

Here is a Copy of the item details of the first item I tried - but it happens to all items.  I have yet to see anything work since the 0.7.11 patch.
```
Item Class: Rings
Rarity: Unique
Kikazaru
Topaz Ring
--------
Requirements:
Level: 20
--------
Item Level: 46
--------
+30% to Lightning Resistance (implicit)
--------
+14 to all Attributes
32% increased Mana Regeneration Rate
40% reduced Effect of Curses on you
Regenerate 1 Life per second per Level
--------
Hear no evil.
```

**Comment by AbeLincoln** [comment]
In trying to diagnose the issue, I found more specific behavior.  Every query I make fails.  However, if I make a request after I have filled my clipboard, the request goes through for the contents of my clipboard, not the object I am hovering over.
This only works once, the clipboard contents seem to "expire" after one search.

**Comment by AbeLincoln** [comment]
I have a workaround now - if I copy the item to my clipboard, the hotkey works as expected.  I just can't hover over an item and use it like before.

My instinct tells me this might actually be an issue with how my PC interacts with the Copy and Paste macro.  This is the first time I am using the app since enabling Windows "new clipboard" (aka the Windows+V paste option).  I wonder if that interferes with the Copy+Paste buffer if the script pulls from there to search?

I don't know the etiquette of editing issues if information changes - but I can modify this one with this updated info - it doesn't appear to be related to Uniques at all.  It seems like a copy buffer issue.

**Comment by JasonGuaZZZ** [comment]
I have the same issue on my desktop, Even when I copied it to the clipboard(ctrl+alt), it still showed the error: an error occurred while parsing the item. Any update on this?
