### ISSUE TITLE
Bow mod: Damage over Time Multi not appearing

### ISSUE THREAD

**Issue by durew** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#197]
# 🐞 bug report

+50% to Damage over Time Multiplier for Poison Inflicted with this Weapon mod is not appearing on evaluate

- OS:  e.g. Win7 x64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by WhiteFang5** [comment]
I've looked into this issue, and it appears to be working just fine in the latest version (v0.7.14)
![image](https://user-images.githubusercontent.com/4527188/120106778-b7d1d200-c15e-11eb-89f8-4cbc6d607efa.png)
