### ISSUE TITLE
Error when parsing currency with 0.7.12

### ISSUE THREAD

**Issue by Retarjoe** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#199]
Just updated to version 0.7.12 and found that price checking currency gives a parsing error.

Price checking uniques, rares, maps etc works fine, just the currency that gives the error. Any fix to this?

Edit: Fossils, resonators, splinters (breach, legion, delirium), oils, delirium orbs, catalysts, essences also gives an error.

**Comment by pumi** [comment]
+1 error too

**Comment by scafutto20** [comment]
me and my friend with the same issue (including essences, fossils, etc.)

**Comment by duckydoug** [comment]
experiencing this now as well. Essences, fossils, catalysts and some currency eg annulment are showing "an error occurred while parsing item"

**Comment by WhiteFang5** [comment]
This issue has been fixed in v0.7.13
