### ISSUE TITLE
Item modifier search does not work (v0.7.13)

### ISSUE THREAD

**Issue by sniper-sin** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#201]
![image](https://user-images.githubusercontent.com/83152730/115981332-e1329780-a5cd-11eb-96ec-4a7d152584c2.png)

First of all, I deleted all existing poe-overlay files from my pc in safe mode and reinstalled them with the v0.7.13 setup file. 
However, passive search and modify search for other items also do not work properly in cluster jewels.

In the image I attached, this is my search box when I search for an intermediate cluster jewel with 2 notable passives.

Search never worked properly in this league.

**Comment by WhiteFang5** [comment]
Price prediction is provided by poeprices.info, it seems that their prediction returns and error and can't properly predict the price on the fly.  
You can however click the "search" word at the bottom of the dialog to lookup individual price listings (obtained from the official poe trade website).  
  
But perhaps that's no your main issue. You're mentioning notables, but they don't seem to appear in the stat list in your screenshot. Can you perhaps copy-paste the item in a reply to this thread? This'll allow us to investigate what's wrong with the notables.
