### ISSUE TITLE
Leaving party as customer doesnt work (v0.8.0-beta.2)

### ISSUE THREAD

**Issue by bwsdm** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#206]
# 🐞 bug report

**Describe the bug**
When I go to another person's hideout to buy something. I click on my "thx" reply button (cant remember if I edited a button or made a new one) and then I get an error about cannot leave party not found

**To Reproduce**
1. Initiate a buy from someone and make sure the app picks it up (I notice some russian sellers arent picked up)
2. Go to their hideout to pick up
3. Click a button to send them a message (I usually sent thanks)

 
**Expected behavior**
When performing the reproduction steps it should remove the trade from the companion app and pop up with an error at the bottom about cannot leave party not found.

**Screenshots**
![image](https://user-images.githubusercontent.com/2353927/116894044-3a668080-abf7-11eb-8b66-86b81c5908fc.png)

## 🌍  Your Environment

- OS: Win10 x64
- Version: v0.8.0-beta.2
- PoE: Steam 3.14.1 English

**Comment by WhiteFang5** [comment]
This issue was addressed in further development since the beta and leaving party is now supported if you're logged in to your poe account and have your currently active character selected/detected accordingly.
