### ISSUE TITLE
Some Russian Sellers Not Picked Up By Trade Companion (v0.8.0-beta.2)

### ISSUE THREAD

**Issue by bwsdm** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#207]
# 🐞 bug report

**Describe the bug**
I believe this happens when the trade site determines the message to be sent needs to be entirely Russian. The bug is that when I paste the message to buy from a Russian seller the transaction is picked up by the companion and I cannot use the UI to do the trade.

**To Reproduce**
1. Perform a buy from a Russian seller that uses a buy message that is entirely in Russian (I notice some Russian sellers seem to proc messages there are in English except for their tab names.

**Expected behavior**
When you do this you should see the companion not have a buy in progress

**Screenshots**
Ill try to add a screenshot when I trade again

## 🌍  Your Environment

- OS: Win10 x64
- Version: v0.8.0-beta.2
- PoE: Steam 3.14.1 English

**Comment by WhiteFang5** [comment]
This issue has been resolved during further development since the beta. All poe available languages are now supported.
