### ISSUE TITLE
Poe Exchanged bugged out.

### ISSUE THREAD

**Issue by noqualms** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#211]
I get this error after I put in a minimum stock amount and it bugged out, I don't know how to resolve the issue.

https://gyazo.com/5efd82b49381a02f3cb1be6702db6c53

**Comment by WhiteFang5** [comment]
Based on your screenshot (which mentions overwolf), you're actually reporting it at the wrong place. This is the community fork, which uses Electron (and not overwolf) for its development. For the overwolf version I'd like to direct you to: https://github.com/Kyusung4698/PoE-Overlay/issues
