### ISSUE TITLE
Mods stats rounding error [Cluster Jewels]

### ISSUE THREAD

**Issue by kamilrogo** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#224]
# 🐞 bug report

**Number of passive skills in cluster jewels should not be rounded**
When I use any range for mods (ex. -5% to 5%) results are useless for cluster jewel mods:
Adds # Passive Skills AND # Added Passive Skills are Jewel Sockets

If I have Large Cluster with 8 Passive Skills I don't care about 7-9 range. It shouldn't be rounded like that.
(with -5% to 5%): 5% of 8 is 0,4 so range should be 7,6-8,4 and rounding this values we should get: 8-8

If I use 0%-0% range for mods then it is working for cluster jewels but overlay is useless for every other item...

**To Reproduce**
1. Go to Stash
2. Hover over any Cluster Jewel
3. Ctrl + D
4. See useless info

**Expected behavior**
Stats should be rounded to the closest INT value.
Don't use "rounding down" for "min" value and "rounding up" for "max value" - just respect % range and round to the closest INT.

**Screenshots**
![Clipboard01](https://user-images.githubusercontent.com/27273043/123430453-7e0eb280-d5c8-11eb-9b1a-eb4a222e5525.png)
![Clipboard02](https://user-images.githubusercontent.com/27273043/123430462-80710c80-d5c8-11eb-89cc-9d0fce9255bf.png)

## 🌍  Your Environment

- OS: Win10 x64
- Version checked: 0.7.14 and 0.8.0-beta2
- PoE: GGG Client

**Comment by WhiteFang5** [comment]
This issue has been on the back of my mind for a while, and I (finally) found some time to work on a proper solution: A special processor for cluster jewels so both "added passives" and "item level" are assigned appropriate ranges based on notable threshold levels and min-passives needed to grab the socket(s).  
This change will be available and enabled by default in the next release.

**Comment by WhiteFang5** [comment]
A toggle to enable/disable processing of cluster jewels to highlight specific stat ranges by default was added in v0.8.10
