### ISSUE TITLE
Windows' Aero Snap for settings window is nonfunctional

### ISSUE THREAD

**Issue by TacticalMook** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#229]
Aero Snap is the feature that lets you drag a window to a screen border to maximize it, or dock it to the left half, right half, or a quarter corner of the screen.

This might point you in the right direction: [https://stackoverflow.com/questions/2920451/aero-snap-not-working-for-my-application](https://stackoverflow.com/questions/2920451/aero-snap-not-working-for-my-application)

**Comment by WhiteFang5** [comment]
Thanks for reporting this, it seems to be an issue that is fixable. We'll look into fixing it for one of our next releases.
(Source: https://stackoverflow.com/a/63101964)

**Comment by WhiteFang5** [comment]
After some further investigation, it seems that there is some Electron issue that we can't simply fix. So we can't/won't fix this for now.
