### ISSUE TITLE
Stopped working in Russian client 3.15 POE

### ISSUE THREAD

**Issue by 9564519** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#233]
Please, help! Apologies in advance, using translate.google.com

# 🐞 bug report

The program stops calling "settings" after enabling the "Russian" language in the client
poe-overlay-0.8.1.exe WORKED BEFORE 3.15.0 Path of Exile: Expedition

**To Reproduce**
1) https://ibb.co/5Bt7MvM I choose - I save
When saving, the data is overwritten in %AppData%\Roaming\poe-overlay\
2) https://ibb.co/3zFY5JZ I repeat opening the settings - There is nothing.
---
The process does not close normally.
We remove the process with administrative resources
Restart - the program starts.
https://ibb.co/F8C6bqD
When you try to open the settings - Nothing happens. (Procmon64.exe see that the program is trying to "write" "read", with the file c:\Program Files (x86)\Grinding Gear Games\Path of Exile\logs\Client.txt)
When you try to open the Reset zoom - Nothing happens.
When you try to open the relaunch - Nothing happens.
When you try to open the Exit - Nothing happens.
The remaining buttons work.

!!! The program restores its work if cleaned c:\Users\admin\AppData\Roaming\poe-overlay\ !!!
But it only works with the game client in English.

**Expected behavior**
Please help me!

## 🌍  Your Environment

Because of what I wrote, I thought I had a problem.
OS is reinstalled on:
- OS win 10 21h1 10.0.19043.1110: https://ibb.co/SKy3pkZ
- Version: I have tried all possible software options 
- (poe-overlay-0.8.2.exe + poe-overlay-Setup-0.8.2.exe)
- And also I tried to use the old version: poe-overlay-0.8.1.exe)
- PoE: tested in NO STEAM ver.

**Comment by WhiteFang5** [comment]
Hi, thank you for reporting this issue. An earlier report by a Korean player was submitted through discord and it appears that any languages that don't use the latin-alphabet have this issue/bug.  
We have a fix scheduled for the next release, which should arrive later today after some additional issues have been fixed.

**Comment by 9564519** [comment]
Thanks a lot.
I was so afraid that these were my personal problems.

**Comment by WhiteFang5** [comment]
The fix has been release in v0.8.3
