### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by fatfat664** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#237]
Hi, my app does not auto update even though I'm running it as admin and I have auto update enabled. I've tried relaunching the app and it doesn't update, I have to uninstall and install the latest release every time. Please help. ty.

**Comment by WhiteFang5** [comment]
Currently (v0.8.0 - v0.8.3) auto-update is broken and it'll take two more updates to get it fixed. Unfortunately you'll have to manually update until it has been fully fixed.

**Comment by WhiteFang5** [comment]
A first fix attempt has been release in v0.8.4 ; This should hopefully restore auto-updating to the next version once it's released.

**Comment by WhiteFang5** [comment]
Another update (0.8.5) has been published. If everything went well on the previous release, 0.8.4 should auto update itself to 0.8.5 ; please let us know if that's not the case.

**Comment by fatfat664** [comment]
I just tested it and it worked when I relaunch the app. Thanks!
