### ISSUE TITLE
Error "2:Invalid Indexed type" Try Again?

### ISSUE THREAD

**Issue by EURO-KOLYAN** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#239]
# 🐞 bug report

Push "ctrl+d", autosearch 0,5 sec and  get this error

## 🌍  Your Environment

- OS: Win10 x64
- Version: 0.8.3-0.8.3 setup
- PoE: Steam 3.15.0d Ru

**Comment by scafutto20** [comment]
It works if you change the "searching time period" from 'Any Time' to any other.

**Comment by EURO-KOLYAN** [comment]
> It works if you change the "searching time period" from 'Any Time' to any other.

Ok. thanks. it's really work)
