### ISSUE TITLE
2: Invalid Indexed Type error

### ISSUE THREAD

**Issue by Rasmusmp** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#240]
When evaluating an item I get an error "2: Invalid Indexed Type"
This happens an all item evaluations, unique, rare, normal, currency, etc.  

![image](https://user-images.githubusercontent.com/12305592/127286438-43ddb8ed-9da9-4366-86df-6103363cc12e.png)

## 🌍  Your Environment

- OS: Win10 x64
- Version:  0.8.3
- PoE: Steam 3.15.0d English

**Comment by Skyyofficial** [comment]
I was on 0.7.11 and had the same bug, updated and still happens. Might be because of the new PoE patch

**Comment by scafutto20** [comment]
It works if you change the "searching time period" from 'Any Time' to any other.

**Comment by HankTheDrunk** [comment]
> 
> 
> It works if you change the "searching time period" from 'Any Time' to any other.

As a temp solution to this problem, this works.

**Comment by TechTrooper** [comment]
Is there any way to change the default search time period? I cba to change it manually from the menu each and every time 😢

**Comment by scafutto20** [comment]
> Is there any way to change the default search time period? I cba to change it manually from the menu each and every time 😢
> 
> EDIT: Found it
> ![image](https://user-images.githubusercontent.com/3955313/127582308-d3c0ab8a-45b4-41e6-8500-45b5cc3b8434.png)

The new version fixes this issue as well.

**Comment by WhiteFang5** [comment]
This bug was fixed in v0.8.4
