### ISSUE TITLE
Can't search Immunity Flask Mods

### ISSUE THREAD

**Issue by scafutto20** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#241]
Can't search these flask mods anymore:

Immunity to Chill/Freeze
![image](https://user-images.githubusercontent.com/46674520/127412451-5d883ed6-3b46-4870-9b69-fa1358a0941a.png)

Immunity to Bleeding/Corrupted Blood
![image](https://user-images.githubusercontent.com/46674520/127412496-15e438f4-1620-4a7e-ad52-f446f4e27d03.png)

- OS: Win10 21H1
- Version: 0.8.3
- PoE: 3.15.0d

**Comment by WhiteFang5** [comment]
Thanks for reporting this. We have to update the poe overlay assets for this. This update is scheduled for the next release.

**Comment by WhiteFang5** [comment]
The new mods should be available in v0.8.4
