### ISSUE TITLE
Second monitor video going black

### ISSUE THREAD

**Issue by OlympusX** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#242]
Having an issue where every time I price-check an item, any video I have playing on my 2nd monitor goes black. Specifically Youtube videos or Twitch streams. The audio still plays normally but the video goes out. Running as administrator

**Comment by Kompas9** [comment]
Exactly the same, running RTX 3080 with 3440x1440 + 2560x1080 monitors. 
0.7 version works perfectly, but after 0.8 if YT video is playing, it goes black, you need alt-tab back to video window and it goes back normal.

**Comment by vklages** [comment]
Same here, after going from 7.x to 8.x my second monitor (mostly showing twitch) goes dark.
I'm using a RX 5700 XT, black screen is 2560x1440, main screen is 1920x1080.

**Comment by WhiteFang5** [comment]
Right click the tray icon in your task bar at the bottom right and disable hardwareacceleration. This should fix the blackscreen.
