### ISSUE TITLE
Kakao Client cannot use Trade companion.

### ISSUE THREAD

**Issue by neo6633** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#243]
# 🐞 bug report

**Describe the bug**

Im kakao client player. It may not loading client.txt file correctly.
Our client.txt file is not client.txt to KakaoClient.txt

And default location is 'C:\Daum Games\Path of Exile\logs'

**To Reproduce**

**Expected behavior**

https://pastebin.com/BxTL5KL4
here is my KakaoClient.txt
there should be notable letters here.
2021/07/31 00:26:58 4372781 bb1 [INFO Client 7656] **@수신** <ÊraS> Pepechil_gg: Hi, I would like to buy your Sorrow Stinger Great White Claw listed for 1 chaos in Expedition (stash tab "~b/o 1 chaos"; position: left 18, top 7)

@수신 also may could be a problem. 

**Screenshots**

https://i.imgur.com/BlIkhWr.png

## 🌍  Your Environment

- OS:  Win10 x64
- Version:  0.8.4
- PoE:  Kakao client Korean

**Comment by WhiteFang5** [comment]
Thanks for the info. We'll look into adding a way to detect if the Korean client is being used or not and adjust the file name accordingly. Maybe you can tell us what the client exe name is?

**Comment by neo6633** [comment]
> 
> 
> Thanks for the info. We'll look into adding a way to detect if the Korean client is being used or not and adjust the file name accordingly. Maybe you can tell us what the client exe name is?

PathOfExile_KG.exe

**Comment by WhiteFang5** [comment]
Thanks. I also noticed we already have the client exe names in another file. So we can use those to detect if it's the Korean client or not and change which log txt we check/use for the trade companion.

**Comment by neo6633** [comment]
Thanks. This app is really good! :)))

**Comment by WhiteFang5** [comment]
Kakao client logs are now supported (in v0.8.5+)

**Comment by neo6633** [comment]
Its not supported. I tried english kakao client and it is doing well now. Think it read **KakaoClient.txt** well.

but with korean language poe client, it didnt work.

And I found the reason,

**[English kakao Client log]**
2021/08/09 10:20:08 973984 bb1 [INFO Client 12604] @From QualityRizlaPaper: Hi, I would like to buy your Hexproof Blueprint: Tunnels of Skirmishing listed for 10 chaos in Expedition (stash tab "~b/o 10 chaos"; position: left 10, top 9)


**[Korean kakao Client log]**
2021/08/09 09:45:56 3565859 bb1 [INFO Client 12464] @수신 expmw: Hi, I would like to buy your Deployed Blueprint: Smuggler's Den listed for 8 chaos in Expedition (stash tab "~b/o 8 chaos"; position: left 10, top 10)


It is having a difference of @From and @수신

**Comment by neo6633** [comment]
@WhiteFang5

**Comment by WhiteFang5** [comment]
I've checked the trade regexes (https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/blob/master/src/assets/poe/trade-regexes.json#L23) and it seems the Korean words for "from" and "to" are missing. Can you provide both of them as they appear in the client logs? Then I can add them and ship the fix with the next release.

**Comment by neo6633** [comment]
@from = @수신
@to = @발신

**Comment by neo6633** [comment]
"from" = "수신"
"to" = "발신"

@WhiteFang5

**Comment by WhiteFang5** [comment]
The from & to key-words were added and this issue should be fixed now. Please re-open if it still persists (as I have no way of actually testing this)
