### ISSUE TITLE
Suggestion: Option to disable price prediction

### ISSUE THREAD

**Issue by Ieremies** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#244]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

I use PoE overlay a lot, and when I'm playing SSF is also super useful to compare some stats. For example, is way easier to use the evaluate feature to check the total resistance of an item or the DPS of an amour then to do it by looking in game. Obviously I disabled the initial search, since I'm playing SSF, but there is no way to disable the price prediction, which would be a nice feature, for me at least.

**Describe the solution you'd like**

Some configuration option to disable price prediction.

I know that will not be a suuuper high priority request, but it would be nice (also for trade leagues, since, at least for me, it isn't super useful)

**Comment by WhiteFang5** [comment]
A toggle has been added in v0.8.10 to show/hide both trade predictions (from poeprices.info) as well as exchange rates (from poe.ninja)
