### ISSUE TITLE
Invalid Query

### ISSUE THREAD

**Issue by nexoske** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#249]
I'm running the latest version but i'm  getting invalid query?
How can i fix this?

![image](https://user-images.githubusercontent.com/28025361/128834388-494629d6-d83f-490e-84e9-d585e6b4d53a.png)

**Comment by WhiteFang5** [comment]
I've check this item using v0.8.5 and it seems to be working just fine.

![image](https://user-images.githubusercontent.com/4527188/129269743-4a721cb9-f406-49e6-ac0c-f9508cdcb78a.png)

**Comment by nexoske** [comment]
I get this with every item... not just the example.

**Comment by WhiteFang5** [comment]
Can you take a screenshot of the price-check settings by clicking the kind of "wifi" icon in the top-left when price-checking an item?  
Maybe your league or currency hasn't been properly set?

**Comment by nexoske** [comment]
I found a way to fix it.
Deleted all my appdata files concerning the overlay.
Then fresh install and to be sure reseted all settings.
Now it's working like a charm :)
