### ISSUE TITLE
Currency Search Doesn't Respect Age

### ISSUE THREAD

**Issue by Reithan** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#251]
# 🐞 bug report

**Describe the bug**
When searching prices for currency, it seems to pull entries of all ages, rather than limiting it to the age I've set

**To Reproduce**
1. Go to an exalt
2. Click on your appraise hotkey
3. Select list view
4. Look at ages

**Expected behavior**
If I set overlay to "show up to 1 day old" it should only show 1 day old postings

**Screenshots**
![image](https://user-images.githubusercontent.com/7475701/129493006-238c013e-6b0a-4c1a-8249-4bfce3642ed3.png)

## 🌍  Your Environment

- OS: Win10 home
- Version: 0.8.5 installed
- PoE: Steam

**Comment by WhiteFang5** [comment]
This happens for all (with a few exceptions) items that can be bulk-exchanged and is a limitation on GGG's end where we cannot add/use the "show up to X days/hours old" feature.
