### ISSUE TITLE
Login stuck on cloudfare check and cannot see private league

### ISSUE THREAD

**Issue by Haroldyolo** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#257]
# 🐞 bug report

**Describe the bug**

Login stuck on cloudfare check and cannot see private league

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/16403781/138593302-cce30608-9f23-494c-96b0-86fff0ccf63e.png)
![image](https://user-images.githubusercontent.com/16403781/138593314-074eefe2-c742-4ab8-9bc0-fe480df5212a.png)

## 🌍  Your Environment

- OS: Win10
- Version: 0.8.7
- PoE: 3.16

**Comment by WhiteSammy** [comment]
https://i.gyazo.com/5b29a1a67a4b16eb69b82d622c9fee55.mp4

**Comment by WhiteFang5** [comment]
> This is still an issue.
> 
> https://i.gyazo.com/5b29a1a67a4b16eb69b82d622c9fee55.mp4

Thank you for reporting this. It has also been reported in the Discord channel. A fix/workaround will be made in the next release.
