### ISSUE TITLE
Suggestion: Add the Hacktoberfest topic to make PRs eligible for rewards

### ISSUE THREAD

**Issue by max-arias** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#258]
Hey there,

I'm looking for something to contribute to during [Hacktoberfest](https://hacktoberfest.digitalocean.com/), would you guys be willing to add the topic for this last week so merged PRs count towards the goal?

Thanks

**Comment by WhiteFang5** [comment]
I'm unfamiliar with Hacktoberfest or how it's supposed to work.  
In terms of topics, there are plenty of "enhancement" labelled issues that can serve as appropriate, often small, features that can be completed.
