### ISSUE TITLE
App login issue

### ISSUE THREAD

**Issue by SanjeninNagi** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#273]
# 🐞 bug report

**Describe the bug**
After going through with the login and getting back into the app, nothing changes, still asks for login.

**To Reproduce**
Login, close web window and get back to app.

**Expected behavior**
After the process the app should see I'm logged in and let me operate changes like switching leagues.

**Screenshots**

## 🌍  Your Environment

- OS:  Win10 64
- Version:  0.8.10 portable
- PoE:  e.g. Kakao 3.17 kor

**Comment by WhiteFang5** [comment]
Can you check for any errors in the application log?  
(The log can be found here: `%appdata%\poe-overlay\logs\main.log` - feel free to attach the entire log file)

**Comment by SanjeninNagi** [comment]
This does not remain in the log because it does not appear as an error.
Instead, I attach a video about the symptoms.

https://www.youtube.com/watch?v=AbwY7oLwoqs

**Comment by WhiteFang5** [comment]
Ah, i see. The video does make it clear now. 
Poe overlay cf was never tested using the kakao login method. It looks like it simply doesn't work. I don't understand enough of the Korean language to look into this and fix it, sorry.

**Comment by WhiteFang5** [comment]
I've looked into some code of poe overlay cf related to logging in, and it seems I've only covered the official poe website and didn't add the domain names for other languages.  
I'll apply a fix, so perhaps that solves the login issue. The fix should be available in the next release (v0.8.11)

**Comment by SanjeninNagi** [comment]
Thank you for solving it.
I hope there will always be good things.
