### ISSUE TITLE
v0.8.10 - Kirac Mission Map Box

### ISSUE THREAD

**Issue by Taffa2** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#278]
# 🐞 bug report

**Describe the bug**
When pressing ctrl-shift-m on a Kirac Mission Map you get an error: Item could not be parsed: Please make sure you have the correct language selected.

**To Reproduce**
1. Click on your map device
2. Click on Kirac Mission
3. It then shows all the maps available to do Kirac missions
4. Hover your mouse icon over any map and do ctrl-shift-m
5. Observe the error message

I am using EN POE and EN OCF

**Expected behavior**

Pressing ctrl-shift-m would open the OCF info box on the map

**Screenshots**
![Kirac](https://user-images.githubusercontent.com/15445697/153736355-7c6a9860-4c97-4b93-bcad-98dd8397b0d6.jpg)

## 🌍  Your Environment

- OS:  Win10 x64
- Version:  0.8.10 portable
- PoE:  3.17 English

**Comment by WhiteFang5** [comment]
This is an issue in PoE itself where you can't copy-paste the map shown in Kirac's Mission selection interface.  
Unfortunately we can't do anything about this, it's up to GGG to change this behaviour.
