### ISSUE TITLE
Suggestion: Add missing Map Modifier

### ISSUE THREAD

**Issue by Imiona** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#279]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

The Mod "Players have 60% less recovery rate of life and energy shield" is missing from the Map Options

**Describe the solution you'd like**

Add it pls, its important for RF Builds

Thx

**Comment by WhiteFang5** [comment]
This modifier is already in the list, but appears to have a missing translation. We'll look into fixing the translation.  
Meanwhile you can find it by searching for it's untranslated name:
![image](https://user-images.githubusercontent.com/4527188/154121673-f2d04b6e-db23-4f63-9321-7d7023c5b35f.png)

**Comment by Imiona** [comment]
thx
