### ISSUE TITLE
Mod: Forbidden Flesh and Flame mods mixed up 

### ISSUE THREAD

**Issue by Fugaron** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#282]
Forbidden Flesh and Flame searches look for the same ascendency passive on the same jewel type, resulting in an impossible criteria therefore there are always no results.

E.g. on a Forbidden **Flesh** jewel, the search currently looks for the passive on a Forbidden **Flesh** jewel, while it should look on Forbidden **Flame** jewels, and vica versa. 

I was able to replicate it across 2 Forbidden Flame and 1 Forbidden Flesh jewels.

# 🛸 Item modifier report

**As it appears in-game**
![image](https://user-images.githubusercontent.com/103990380/163959201-49b71f41-9bec-4d6a-aad7-cbb45e0b7bf8.png)

**As it appears in Overlay**
![image](https://user-images.githubusercontent.com/103990380/163959145-2fd82047-ed48-4740-b6c1-a712c046814a.png)
It still shows the correct mod. Also "no results".

**As it is sent through to the browser**
![image](https://user-images.githubusercontent.com/103990380/163959071-ce76a6e4-dd25-4f9b-8680-45a0d9836ea7.png)

Here the mods are already mixed up. If I change the filter in the browser from "_Allocates # if you have matching modifier on Forbidden Flame_" to "_Allocates # if you have matching modifier on Forbidden Flesh_" it works and shows results. Otherwise, no results. I'm guessing the API call makes the same mistake but I can't printscreen that.

## 🌍  Your Environment
- Version:  0.8.14 installer
- PoE:  3.17.3b English

**Comment by WhiteFang5** [comment]
Thank you for reporting this issue. It'll be fixed in the next release (v0.8.15)
