### ISSUE TITLE
Mod: Void Battery - Inc global crit chance is missing

### ISSUE THREAD

**Issue by Fugaron** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#283]
Void Battery search doesn't pick up Increased Global Critical Strike Chance mod. The example shown here is corrupted enchanted but a regular Void Battery produces the same outcome.

# 🛸 Item modifier report

**As Overlay picks it up**
![image](https://user-images.githubusercontent.com/103990380/163961617-1f72b74c-16c2-4269-a01f-e96ae1ab988b.png)

**Expected item modifier**
![image](https://user-images.githubusercontent.com/103990380/163961992-e0c151b5-b635-407c-ab4b-4f5a7a17c892.png)

**Copied item data**

```
Item Class: Wands
Rarity: Unique
Void Battery
Prophecy Wand
--------
Wand
Physical Damage: 35-64
Critical Strike Chance: 8.00%
Attacks per Second: 1.20
--------
Requirements:
Level: 68
Int: 245
--------
Sockets: G-B-B 
--------
Item Level: 84
--------
Quality does not increase Physical Damage (enchant)
Grants 1% increased Area of Effect per 4% Quality (enchant)
--------
13% chance to gain Unholy Might for 3 seconds on Kill (implicit)
--------
80% reduced Spell Damage
20% increased Cast Speed
60% increased Global Critical Strike Chance
+49 to maximum Mana
+1 to Maximum Power Charges
25% increased Spell Damage per Power Charge
--------
"The trick is to give nothingness,
and to receive everything in return."
- Inquisitor Maligaro
--------
Corrupted

```

**Screenshots**

## 🌍  Your Environment

- Version:   0.8.14 
- PoE:  3.17.3b English

**Comment by WhiteFang5** [comment]
Thank you for reporting this issue. It'll be fixed in the next release (v0.8.15)
