### ISSUE TITLE
v0.8.14 Japanese problem

### ISSUE THREAD

**Issue by ao41O** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#286]
# 🐞 bug report

**Describe the bug**

language setting to Japanese, the Overlay crashed.

**To Reproduce**

Set the overlay language setting to Japanese and restart.
Overlay crashed.

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win10 x64
- Version:  e.g. 0.8.14
- PoE:  e.g. Steam 3.17.4 japanese

**Comment by WhiteFang5** [comment]
This should now be fixed in v0.8.21
