### ISSUE TITLE
Error searching: Unkown filter group_ sentinel_filters

### ISSUE THREAD

**Issue by victorgonzcuriel** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#298]
# 🐞 bug report

**Describe the bug**
When i try to search something, it returns this errors.

**To Reproduce**
Just search something with Ctrl+D and a basic filter

**Screenshots**

https://i.imgur.com/0CF9rtR.png
https://i.imgur.com/px8MQcU.png

## 🌍  Your Environment

- OS: windows 11
- Version: 0.8.18
- PoE:  e.g. Steam 3.19.0/English

**Comment by St0rmal0ng** [comment]
I have this same issue. It also detects the current league as the Sentinel league... which may be related. You have to manually set it to Kalandra.

**Comment by ColdFaith** [comment]
I have the same problem. 

OS: Windows 10
Version 0.8.18
PoE: Steam 3.19.0/English

**Comment by victorgonzcuriel** [comment]
Directly select my character fixed the issue fyi

**Comment by melink14** [comment]
Manually selecting Kalandar and my character had no effect on this bug for me!

**Comment by camwu** [comment]
I have this issue as well. My character and league have been properly identified and selected in the Settings menu.

![image](https://user-images.githubusercontent.com/55898774/185771079-2a7e8ced-fc09-4169-ba7b-f1966f960b42.png)

![image](https://user-images.githubusercontent.com/55898774/185771095-0dbd188e-7395-4b40-a12c-390acd84ac8e.png)

**Comment by WhiteFang5** [comment]
Thank you for reporting this issue, it was fixed a while ago (in v0.8.19), so I'm going to close this ticket.
