### ISSUE TITLE
100% support for Harvest League features

### ISSUE THREAD

**Issue by ijemafe** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#3]
Each league, libggpk is used to parse data (items, maps, etc.) and add it to PoE-Overlay. We should automate this process and add the resulting files for Harvest League.

**Comment by WhiteFang5** [comment]
I am working on a pipeline/cli app that can extract the data from the ggpk and export it in the json format used by the PoE Overlay app.

**Comment by ijemafe** [comment]
@WhiteFang5 Do you have a Git repo somewhere? We can help contribute as this is probably the highest priority for PoE-Overlay currently.

**Comment by WhiteFang5** [comment]
@ijemafe I started off with a sub folder in the CF. Since it's completely standalone, I'll make my own repo. Perhaps it's possible to add a repo for this under the poe overlay fork group, I've seen multiple other repos grouped under the name. I've currently dubbed the app PoEAssetUpdater.

**Comment by WhiteFang5** [comment]
@ijemafe I've pushed my code into a new repo which I've made under my user for now ( https://github.com/WhiteFang5/PoE-Asset-Updater ).  
We should perhaps look into moving it to the "PoE Overlay Community" group?

**Comment by WhiteFang5** [comment]
@ijemafe Some days ago I've updated the poe asset data and removed the WIP from my PR. For the past few days I've been using a dev build in-game and havn't found any major issues. Any issues found are covered by other PRs I've submitted.
