### ISSUE TITLE
Cannot ctrl-d on Bone Ring

### ISSUE THREAD

**Issue by Taffa2** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#301]
Item Class: Rings
Rarity: Rare
Brimstone Whorl
Bone Ring
--------
Requirements:
Level: 35
--------
Item Level: 48
--------
Minions have +10% to all Elemental Resistances (implicit)
--------
+29 to Strength
Adds 1 to 2 Physical Damage to Attacks
+37 to maximum Mana
Minions have +13% to all Elemental Resistances

![bone ring](https://user-images.githubusercontent.com/15445697/185878792-6e6bd7ae-0ca3-4706-b118-321539a92952.jpg)

![bone ring error](https://user-images.githubusercontent.com/15445697/185878810-8b48966d-565d-4d1d-80f5-431400f03ab0.jpg)

Language is set to English, league is set to Kalandra

**Comment by WhiteFang5** [comment]
Thank you for reporting this issue. It'll be fixed once 3.19 support is release in the next version of poe overlay (v0.8.20)
