### ISSUE TITLE
Trade Companion not displaying Incoming/Outgoing trades

### ISSUE THREAD

**Issue by JamieBunpup** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#304]
Whispering myself creates an incoming/outgoing trade notification, however my outgoing buy messages or incoming buy messages to/from other players doesn't create a notification.

Running on Win 10

**Comment by JamieBunpup** [comment]
It seems that the issue is the new embedding on trades from the bulk currency part of Pathofexile.com/trade

Items display just fine, but when it's embedded with the item requested in game it doesn't trigger.

![image](https://user-images.githubusercontent.com/71115700/187109195-af20caa9-8a4c-4b84-90c2-69e9645ed3fb.png)

**Comment by Bresch90** [comment]
Adding to this: At a glans it seems to be because the wording is diffrent when using the embedded using "I would" instead of "I'd" as usual.

**Comment by WhiteFang5** [comment]
If I'm not mistaken, this bug was spotted by multiple people and a fix has been made. The fix will be included in the next release (v0.8.20).
