### ISSUE TITLE
Suggestion: Plz don't let login account depends on game language settings.

### ISSUE THREAD

**Issue by archanfel777** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#308]
# 🚀 feature request
Hello.
I am a user who is playing PoE in Korean settings.
But my account still belongs GGG not Kakao(Korean PoE publisher), so I cannot play on Korean servers managed by Kakao.
(Of course, also client is from GGG.)
And I have no intention of transferring my account to Kakao in the future.
Under these circumstances, I tried to use PoE-Overlay, and that ended in failure.
Bcoz, PoE-Overlay asks me to log in with my kakao account when I change the language of game settings on PoE-Overlay to Korean.
So I would like to ask you to make account login of PoE-Overlay not depends on the language of game settings.

**Describe the solution you'd like**
If possible, I would like to be able to set the language of game settings and the publisher of the login account separately.

Thank you for your support.

**Comment by WhiteFang5** [comment]
Thank you for this suggestion. It'll take a bit of work to make a change where the overlay language isn't tied to a specific poe login webpage. In the meantime you can probably change poe overlay's language to English, login, then change the language back to korean.

**Comment by archanfel777** [comment]
> Thank you for this suggestion. It'll take a bit of work to make a change where the overlay language isn't tied to a specific poe login webpage. In the meantime you can probably change poe overlay's language to English, login, then change the language back to korean.

Thx for your answer.
Already I had tried that way it ended in failure.
Eventhough I change the language setting to English and log in with GGG account,
when I change the language setting back to Korean,
PoE-overlay asks me to log in with kakao account.
If I ignore that request and trigger PoE-overlay on the game,
it tells me that need to login to use PoE-overlay.
Can this issue improve for 3.20 league?

**Comment by WhiteFang5** [comment]
A new setting has been added called "website language". Changing this language will change which API and webpage is used to login, but doesn't determine which in-game language you're using (for that you'd need to change the language under the "game settings" section of the General tab in the settings menu).  
This should hopefully satisfy this feature request and should allow you to login through the GGG website (by choosing English as web language), but still use Korean as in-game language and game-language in poe overlay.
