### ISSUE TITLE
Mod: Reduced Mana Reserved

### ISSUE THREAD

**Issue by WhiteFang5** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#31]
# 🛸 Item modifier report

The Modifier is being searched incorrectly.
Because It's "reduced", the search value is negative. Due to it being negative, you have to put the "min" in "max" and visa versa. in order to search "1% reduced or more"

**Item modifier**
% Reduced Mana Reserved

**Copied item data**

```
Rarity: Unique
Conqueror's Efficiency
Crimson Jewel
--------
Limited to: 1
--------
Item Level: 1
--------
3% reduced Mana Cost of Skills
4% increased Skill Effect Duration
2% reduced Mana Reserved
--------
The stone may yet bleed.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
--------
Note: ~price 20 chaos
```

**Screenshots**

![image](https://user-images.githubusercontent.com/4527188/84569808-6aabf300-ad89-11ea-9479-6f07bec6b702.png)

Search performed:
https://www.pathofexile.com/trade/search/Standard/yX9D7glcR

Expected:
https://www.pathofexile.com/trade/search/Standard/7ZOwPY2t5

(Note the change in the min/max values of the "#% Increased Mana Reserved" stat filter)

## 🌍  Your Environment

- Version: v0.6.28

**Comment by wratho** [comment]
do we know if, 
![image](https://user-images.githubusercontent.com/28812961/84571699-8055f400-ad5a-11ea-8e0a-94a5d6ce6f52.png) is acceptable here instead of passing nothing to the min??

**Comment by jmclark78** [comment]
I ran searches using both a blank min and -99999, got the same results.
It would also retain consistency with the positive fields.

**Comment by WhiteFang5** [comment]
Yes, `-99999` is actually accepted. I took a deep-dive into the code and found that `ItemSearchFiltersStatsService` does take care of negating and flipping the min & max values.  
The issue here is, that it has to negate the value (since positive numbers are supplied from the copied PoE item) AND has to flip the min/max.  
The stat id `stat_2227180465` is the one being used for the search, in the `stats.json` it has `"negated": false` and a special character `N` in front of the predicate being used for it: `"N#|-1"`. Because negated is false and the `N` is present, the min/max value is being negated by the code, yet the flipping doesn't take place because some lines below ther's actually a statement `if (min >= 0 || !stat.negated)` that prevents the min/max flipping; and I'm not sure if removing this statement would break other stats.

**Comment by wratho** [comment]
yea so the negated flag is for things that are actually called 'Reduce' where in this instance the reduce mod on the item is a negative amount of increase search mod. So i think i actually have a working if check that allows it to continue swapping in this instance just requires a bit more thinking and testing to make sure im not messing more stuff up.
