### ISSUE TITLE
App stops responding when language is switched to Japanese

### ISSUE THREAD

**Issue by Alicemetic** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#312]
# 🐞 bug report

**Describe the bug**
When switching language to Japanese, league is not selectable and application is unresponsive even after restarting.

**To Reproduce**
1. Run the app and open settings window
2. Switch language to Japanese ('settings.languages.japanese' in the pull-down)
3. Hit 'Refresh'
4. Any league doesn't appear, so hit 'Save' and close the window
5. The app stops working and the settings screen cannot be reopened even after restart the app

**Expected behavior**
After switching language to Japanese, leagues can be selected from the pull-down.

## 🌍  Your Environment

- OS: Win10 x64
- Version: 0.8.20 Portable
- PoE: Steam 3.20.0 Japanese

**Comment by WhiteFang5** [comment]
Japanese isn't fully supported in 0.8.20 ; With the 0.8.21 release we added full support for Japanese. Please check if the issue still exists in the new version.
