### ISSUE TITLE
2nd monitor freezing video while using app.

### ISSUE THREAD

**Issue by Oddwin** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#313]
# 🐞 bug report

**Describe the bug**
It took me a while to narrow it down. The only reason I noticed was a friend was raving about Awakened POE Trade. This problem doesn't exist when POE Overlay is disabled. 

- Twitch, Youtube, and Discord (friend streaming) freeze the video randomly while using POE Overlay. 

**To Reproduce**
Just play the game while having a youtube/twitch/discord stream up on 2nd monitor. It is completely random. Sometimes I can watch for over an hour without interruption, however, sometimes it happens 10 times in a matter of minutes. 

**Expected behavior**
this only started happening this league. 

**Screenshots**
Not sure a screenshot of a frozen video on Youtube will help?

## 🌍  Your Environment

- OS: Win10 x64
- Version: Paid for and fully updated. 
- PoE: 3.20 - Steam. 

This is BY FAR the best POE tool IMO. Thank you for your time.

**Comment by WhiteFang5** [comment]
Do you happen to have on either your browser or poe overlay the option for "hardware acceleration" enabled? This might be an issue if it's enabled when using both a browser (on a second monitor) & poe overlay.

**Comment by Oddwin** [comment]
> 

Sorry, the Holiday week got away from me. I'll look into this.

**Comment by Oddwin** [comment]
> > 
> 
> Sorry, the Holiday week got away from me. I'll look into this.

Absolutely fixed it! Thank you so much.. it's been making me crazy!
