### ISSUE TITLE
I cannot login to connect the app with pathofexile.com account

### ISSUE THREAD

**Issue by najty** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#322]
# 🐞 bug report

**Describe the bug**

When I open the app and go click to login, I get the I am human checkbox verification, which I click and it then spins around for a moment while "Checking if the site connection is secure" and in couple of seconds goes back to the human verification. Goes back and forth forever. Tried to reinstall the app via update folder, tried to turn off virus protection and firewall. Last time I tried couple of weeks ago all worked fine. PoE site is working in browser fine. Log attached.

**To Reproduce**

1. Open app, go to General tab
2. Click on 'Login' under PoE Account
3. Click on the checkbox to verifiy you are indeed a human
4. Goes to Checking if the connection is secure
5. Goes back to the checkbox to verify human

**Expected behavior**

Login to PoE account 😄

**Screenshots**

![image](https://user-images.githubusercontent.com/127684068/224561667-061dc93b-3582-4ef4-b0ea-640973b37d62.png)
![image](https://user-images.githubusercontent.com/127684068/224561676-737d5e73-590c-4d6f-8b0c-27d9f6c24391.png)

## 🌍  Your Environment

- OS:  Win10 x64
- Version:  0.8.21
- PoE:  Steam 3.20.0/e English
[main.log](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/files/10951513/main.log)

**Comment by jebo80** [comment]
same problem here

**Comment by Fugaron** [comment]
Same problem. Symptoms:

- usually the Cloudflare check end up in an infinite loop just repeating itself
- sometimes the Cloudflare check doesn't load at all

Login through PoE Overlay - and all features based on being logged in - does not work at all.

**Comment by Triky313** [comment]
Same problem.

**Comment by zrisher** [comment]
Does anyone familiar with the application code know if we can workaround this? Perhaps by manually navigating to an auth url and pasting our authentication token somewhere?

**Comment by najty** [comment]
> ~Does anyone familiar with the application code know if we can workaround this? Perhaps by manually navigating to an auth url and pasting our authentication token somewhere?~
> 
> I was able to workaround this by going to the "Evaluate" page and toggling ON the option "Disable In-Game Browser."

Did not change anything on my side. When I toggle on this option, everything is literally the same when trying to login

**Comment by yman69** [comment]
Have the same issue.  Tried the "work around" which did not work for me.

**Comment by najty** [comment]
Today I reinstalled OS to Windows 11 (by formatting drive, not an upgrade). New PoE Overlay download, new install, still same issue.

**Comment by dantaex** [comment]
same problem for me, stuck in a cloudflare response loop.
switching the in game browser toggle did not change anything. switching from portable to setup install did not resolve either.

**Comment by wratho** [comment]
we hopefully have a fix coming for 3.21 release for this. We are going to investigate a better long term fix for this between now and 3.22

**Comment by najty** [comment]
My issue was resolved with latest update. Thank you very much.
