### ISSUE TITLE
Update Links to SignPath

### ISSUE THREAD

**Issue by SabotageAndi** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#328]
Hi!
I am the Developer Evangelist of SignPath.

Could you change the links to us to https://signpath.io?utm_source=foundation&utm_medium=github&utm_campaign=poe-overlay in the Readme.md?

If you want, I can submit a PR for that.

Thanks!

**Comment by WhiteFang5** [comment]
I have updated the links in the ReadMe.
