### ISSUE TITLE
When trying to log in screen site does not have the login options

### ISSUE THREAD

**Issue by Jstraws** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#334]
# 🐞 bug report

**Describe the bug**
When I hit the login button in the settings of the application the POE site is not showing the option to login. When I open the dev console of the browser that is opened there are errors in the console. I have tried reinstalling, restarting, turning on and off hardware accel, rebooting the entire system and nothing has solved it so far.

**To Reproduce**
1. Go to settings
2. Click on login

**Expected behavior**
I should be able to log in.

**Screenshots**
![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/18311973/0e14c3f6-9e2b-4ef5-bef4-8046546ed08a)

## 🌍  Your Environment

- OS:  Win 10 x64
- Version: 0.8.24 installer
- PoE: Steam 3.21 English

**Comment by jokealle** [comment]
have the same problem since 2-3 weeks on 2 different pc's, both @ win10 nothing was consciously changed (just win updates)

**Comment by Meddloid** [comment]
Should it work again? because i still cannot log in. thx regards

**Comment by houlvic** [comment]
I've found a pseudo-solution.

I'm using DeepL translation with comments from Japan.
Sorry if it's not clear.

Login page >> Back to the main page >> Open Youtube link on the official page >> Login to Google >> Google account management >> Click on Chrome download link >> Go to Google from the link on the bottom left of the official Chrome page >> Search "PoE login >> Find the page where you can login with your email address and password, and you are done!


Translated with www.DeepL.com/Translator (free version)

**Comment by houlvic** [comment]
P.S.

"PoE login" swap " https://www.pathofexile.com/login?no-script "

**Comment by WhiteFang5** [comment]
@houlvic Awesome that you've found the old login page, and it still seems to work too. I'll swap the link in the next update when we get the 3.22 data done as well.

**Comment by WhiteFang5** [comment]
With the latest release (v0.8.25) no more work-arounds are required. The URL has been changed and leads to the no-script URL as mentioned by @houlvic . I've tested it, and it works just fine (for now)
