### ISSUE TITLE
Ctrl+D not reading sanctum relic mods

### ISSUE THREAD

**Issue by Electrized** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#336]
Hey, as of current, magic sanctum relic price checking is not working as intended. Example:

Here I have a basic relic that I dropped from sanctum

```
Item Class: Relics
Rarity: Magic
Boosting Censer Relic of Opulence
--------
Item Level: 85
--------
Monsters have 6% chance to drop Double Aureus Coins
Gain 15 Inspiration at the start of the Sanctum
--------
Place this item on the Relic Altar at the start of each Sanctum run
--------
Unmodifiable
```

And here is the result of Ctrl+Ding the item

![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/29844497/80768dfc-23b9-4c73-b029-a266ad04b367)

The search itself seems to work and does take into account the base item, but the affixes of the item itself are missing. 

Reproduction:
Poe 3.22.0b
Win 10 Pro  Version	10.0.19045 Build 19045

**Comment by WhiteFang5** [comment]
This has been fixed in v0.8.26
