### ISSUE TITLE
Evaluate not grouping resistance mods into pseudo "+#% total ele resistance" or "+#% total resistance"

### ISSUE THREAD

**Issue by duckydoug** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#337]
# 🐞 bug report

**Describe the bug**
When evaluating an item with fire/cold/lightning % elemental resistance as well as chaos resistance, normally it is grouped together in the lower half of the evaluate window with a pseudo mod "+#% total elemental res" and "+#% total res". (Screenshot 1)

This has not been showing up on the evaluate window in the last few days despite not changing any settings.

On the Evaluate settings page, I have tried to make sure that the pseudo mod "+#% total elemental res" and "+#% total res" are in the right side column under "selected" but this does not seem to change the result whether it is under "selected" or "unselected". (Screenshot 2)

Evaluating any item with fire/cold/lightning elemental resistances

**Expected behavior**
When evaluating an item with a combination of % elemental resistance, it is grouped together in the lower half of the evaluate window with a pseudo mod "+#% total ele res".

**Screenshots**
![Screenshot 2023-08-26 223943](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/83102039/23826e0e-7049-4882-9b57-ef6da5f80cdb)

![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/83102039/99f3a04b-22c5-487f-b760-f3422f2e7e28)

## 🌍  Your Environment

- OS: Win 10
- Version: v0.8.25
- PoE: Steam 3.22

**Comment by jokealle** [comment]
Have the same Problem, its gone since last Update! cant activat it in options neither, the setting will not saved

**Comment by WhiteFang5** [comment]
This has been fixed in v0.8.26
