### ISSUE TITLE
Fractured, Synth or Lab Enchant Mod: not shown/highlighted after Update

### ISSUE THREAD

**Issue by jokealle** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#338]
# 🛸 Item modifier report

**Current item modifier**

**Expected item modifier**

**Copied item data**

```
Hover item and press CTRL + C and paste here
```

**Screenshots**

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Jstraws** [comment]
This seems to apply to any enchantment since I also encounter the issue with Annoints on amulets.

**Comment by WhiteFang5** [comment]
This has been fixed in v0.8.27
