### ISSUE TITLE
Cluster jewel implicits missing on evaluate

### ISSUE THREAD

**Issue by thatguy692** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#339]
# 🐞 bug report

**Cluster jewels implicit missing on evaluate**
**ALSO SAME PROBLEM FOR FRACTURED ITEMS**

**CTRL+D on any cluster jewel**

**Expected behavior: Being able to select the cluster jewels implicit**

**Screenshots:**
![cluster](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/45224005/27cc698b-866f-46d3-a081-be67c1b868ff)

## 🌍  Your Environment

- OS:  e.g. Win11 x64
- Version:  e.g. 0.8.26 setup
- PoE:  e.g. Standalone

**Comment by WhiteFang5** [comment]
This has been fixed in v0.8.27
