### ISSUE TITLE
Regression: Height of evaluate window is too big for some items

### ISSUE THREAD

**Issue by ltogniolli** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#52]
# 🐞 bug report

**Describe the bug**
When evaluating some items the evaluate overlay is taller than it should be. Seems to happen mostly with simple items with no properties (currency, skill gems, etc)

**To Reproduce**
1. Evaluate a fossil (or a chaos orb)

**Expected behavior**
Proper overlay height

**Screenshots**
Old:
![EvaluateUnnamedOld](https://user-images.githubusercontent.com/1274148/84727837-57a24a00-af66-11ea-8e05-97706699ae8f.png)
New:
![EvaluateUnnamedNew](https://user-images.githubusercontent.com/1274148/84727849-60931b80-af66-11ea-914a-14d32b2a3a28.png)

**Comment by wratho** [comment]
on the old UI, can you open the filter settings popover and take a screen shot as well? Does it cause the UI to scroll?
