### ISSUE TITLE
Black flash when closing the popup on Vulkan

### ISSUE THREAD

**Issue by Chocapic** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#60]
# 🐞 bug report

**Describe the bug**
Black flash when you close the overlay popup with vulkan

**To Reproduce**

Switch to Vulkan
Start a search on any item with ctrl + d
click on any result in the list to close the popup
> black flash

**Expected behavior**
Just like direct X 11 version, no flash when closing the popup

**Screenshots**

## 🌍  Your Environment
windows 10 family 64 bits
poe overlay 0.6.28
steam lastest version of the game
playing in windowed fulscreen 1440p@120Hz

**Comment by MortiferDec** [comment]
This is a GGG bug. It happens when you have to leave and rejoin the PoE client's window. It can happen from going from one screen to say Chrome on another screen, and then going back to the client.

**Comment by LillieSatou** [comment]
use Windowed mode for the time being. Fullscreen & Windowed Fullscreen are identical.

**Comment by alsmith823** [comment]
It seems GGG has resolved the black flicker issue on their end and this isnt occuring anymore. Closing issue
