### ISSUE TITLE
Readme wrongly says the original PoE Overlay "was converted to closed source"

### ISSUE THREAD

**Issue by Versalkul** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#68]
It seems like Kyusung4698 released the code of the new version(1.0.2) on github a few days ago.
While it may not be possible to use this code without the closed source platform overwolf, it still makes the original PoE overlay open source.
I suggest something like "was converted to require the closed source platform overwolf" instead.

**Comment by wratho** [comment]
I believe the readme now states it was converted to utilizing Overwolf instead. Please reopen if you believe we have still mischaracterized the facts.
