### ISSUE TITLE
Suggestion: CTRL+F search for hovered item in open stash window

### ISSUE THREAD

**Issue by OGv1va** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#73]
The old poe trademacro had a feature to ctrl+f on say a gem in my inventory that would copy the name to clipboard and paste in search box of currently opened stash tab.

Great feature for merges and searching quad tabs of gems fast.

**Comment by wratho** [comment]
this feature is currently bound to alt+f by default 
![image](https://user-images.githubusercontent.com/28812961/88108444-70f27380-cb6e-11ea-874c-aa00fe315a5f.png)
you can rebind it to ctrl+f, but this might interact with the default PoE shortcut.
