### ISSUE TITLE
Bad Translations (German)

### ISSUE THREAD

**Issue by Barry3D** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#76]
There are several translations that should be changed.

![ubersetzung1](https://user-images.githubusercontent.com/55182609/85197869-346bf780-b2e4-11ea-8850-8c771bfa91d9.jpg)
![ubersetzung2](https://user-images.githubusercontent.com/55182609/85197870-36ce5180-b2e4-11ea-8a4a-861f70f4deed.jpg)
![ubersetzung3](https://user-images.githubusercontent.com/55182609/85197873-3a61d880-b2e4-11ea-8614-10f9b6b9aa55.jpg)

The automatic/initial search option should also be changed:
 "Führen Sie die erste Suche aus" -> "Gegenstand automatisch suchen"

**Comment by alsmith823** [comment]
Can you provide correct translations?

**Comment by wratho** [comment]
Did the attached PR fix this issue @Barry3D ?

**Comment by Barry3D** [comment]
At work right now will take a look at it in 4-5 hours.

**Comment by Barry3D** [comment]
Created a PR for this

https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/pull/125
