### ISSUE TITLE
Mod: Chance to Poison on Hit being searched as "local" even though it's global

### ISSUE THREAD

**Issue by Reithan** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#8]
Copying my original bug report from the dead version: https://github.com/Kyusung4698/PoE-Overlay/issues/710

# 🛸 Item modifier report

**Current item modifier**

%# CHANCE TO POISON ON HIT (LOCAL)

**Expected item modifier**

%# CHANCE TO POISON ON HIT

**Copied item data**

```
Rarity: Rare
Hate Barb
Vaal Rapier
--------
One Handed Sword
Physical Damage: 22-87
Elemental Damage: 4-94 (augmented)
Critical Strike Chance: 6.50%
Attacks per Second: 1.30
Weapon Range: 14
--------
Requirements:
Level: 66
Dex: 212 (unmet)
--------
Sockets: G G 
--------
Item Level: 74
--------
+25% to Global Critical Strike Multiplier (implicit)
--------
Adds 4 to 94 Lightning Damage
Attacks have 20% chance to cause Bleeding
27% increased Damage with Bleeding
25% chance to Poison on Hit
35% increased Damage with Poison
18% chance to Blind Enemies on Hit with Attacks
--------
Redeemer Item

```

**Screenshots**

Searching for my item with "Chance to poison" through overlay (Not found)
![image](https://user-images.githubusercontent.com/7475701/82616444-0cbd2e80-9b82-11ea-89a6-1766963a6421.png)
Searching through official trade to make sure it's found (not using "local" version of mod, but global), it is found:
![image](https://user-images.githubusercontent.com/7475701/82616466-1e9ed180-9b82-11ea-9f6a-114fc99ac050.png)
Item I was searching for in my stash:
![image](https://user-images.githubusercontent.com/7475701/82616485-28c0d000-9b82-11ea-8e72-7703b93299e2.png)

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
0.6.28 (2020-05-09) (installed)
- PoE:  e.g. Steam 3.10.0/e English
Current Steam version (3.10.1?)

**Comment by alsmith823** [comment]
After some testing in game chance to poison on weapons appears to be a local modifier

**Comment by Reithan** [comment]
As you can see I had a weapon with chance to poison listed, and it was findable through the official trade site by searching "Chance to poison", but searching "Chance to poison (local)" through the official site, or automatically through the overlay would NOT find the weapon.

**Comment by Reithan** [comment]
Added labels to the screenshots to make what happened a little clearer, hopefully

**Comment by Reithan** [comment]
I'm not sure if this issue also affects the poeprices.info result?

**Comment by versedi** [comment]
@Reithan is that mod from Standard League?

**Comment by Reithan** [comment]
Delirium

**Comment by WhiteFang5** [comment]
I might be able to look into this issue once I have finished the data extraction pipeline (so it's ready before the new league arrives) as this issue likely has to do with mod and stat grouping and conversions from the game to the website, which is based on the extracted poe data that's being used by the app.

**Comment by Reithan** [comment]
Awesome, this was basically the only bug keeping me from swapping over from Awakened. Thank you very much for tackling this, @WhiteFang5
