### ISSUE TITLE
Flask modifiers return Invalid Stat error and fail to pull results

### ISSUE THREAD

**Issue by sweezog** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#80]
# 🐞 bug report

**Describe the bug**

Item evaluation fails on various flask modifiers no matter what kind of range they are searched in
Seems to happen mostly on prefix mods, but I haven't been able to test every mod for flasks. 

**Affected Mods** (Not sure if this list is complete)
P: Alchemist's
P: Experimenter's

**To Reproduce**
Pull up Item Evaluation window on a flask item
Select modifiers and run a search

**Expected behavior**
Should return regular search results, instead returns "No Data Found" followed by "2: Invalid stat provided: Explicit.stat_#########"

**Screenshots**

![image](https://user-images.githubusercontent.com/27177075/85223982-aac43480-b38c-11ea-8811-1c92f5eda81f.png)

![image](https://user-images.githubusercontent.com/27177075/85224087-5a99a200-b38d-11ea-9de4-4f1b98d95b58.png)

## 🌍  Your Environment

- OS:  Win10 64bit
- Version:  0.7.1
- PoE: Steam 3.11.0d English

**Comment by WhiteFang5** [comment]
Can you CTRL+C each of those flasks and paste the copied item data in a new comment please?

**Comment by sweezog** [comment]
<pre>
Rarity: Magic
Experimenter's Granite Flask of Warding
--------
Quality: +10% (augmented)
Lasts 5.80 (augmented) Seconds
Consumes 30 of 60 Charges on use
Currently has 60 Charges
+3000 to Armour
--------
Requirements:
Level: 27
--------
Item Level: 73
--------
Immune to Curses during Flask effect
Removes Curses on use
34% increased Duration
--------
Right click to drink. Can only hold charges while in belt. Refills as you kill monsters.
</pre>

I don't have the exact jade flask from the screenshot anymore, but this quicksilver has the same prefix which is causing that issue.

<pre>
Rarity: Magic
Alchemist's Quicksilver Flask of Heat
--------
Quality: +20% (augmented)
Lasts 3.50 (augmented) Seconds
Consumes 20 of 50 Charges on use
Currently has 50 Charges
40% increased Movement Speed
--------
Requirements:
Level: 16
--------
Item Level: 55
--------
Immunity to Freeze and Chill during Flask effect
Removes Freeze and Chill on use
25% increased effect
33% reduced Duration
--------
Right click to drink. Can only hold charges while in belt. Refills as you kill monsters.
</pre>

**Comment by WhiteFang5** [comment]
It's likely that the stat has changed between 3.10 and 3.11 ; Once we have a release ready with Harvast league stat changes, it should be fixed:
![image](https://user-images.githubusercontent.com/4527188/85309084-5f0bab00-b4b2-11ea-9c30-9e956c8b3ce1.png)
(This screenshot was made using 3.11 stat data in a development build)
