### ISSUE TITLE
Suggestion: Please give me a way to ONLY use MY browser, not the browser control you have

### ISSUE THREAD

**Issue by Xyrm** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#88]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**
I *HATE*, with a BURNING RAGE PASSION, the browser control (or whatever it is) that you open web pages in.  I know you have the tech to open my ACTUAL browser (in my case chrome) because I can open a Wiki or PoeDB page in chrome with the "alternate" keybinds.

**Describe the solution you'd like**
Rather than have multiple keybinds, have a setting that lets us pick "our" browser, versus whatever god awful browser control you guys are using by default, and have that apply to all keybinds, instead of multiple sets of keybinds.

**Describe alternatives you've considered**
I would begrudgingly accept a second keybind slot to open trades from CTRL+D in an ACTUAL browser.

**Additional context**

**Comment by WhiteFang5** [comment]
You can use CTRL+Click to open your actual browser instead of the browser dialog opened by the app.

**Comment by C-Pettersson** [comment]
It would be nice to set "Always open in external browser" under settings.

**Comment by wratho** [comment]
We can investigate adding an option to the settings to change the default browser selection. I am curious why there is an issue with using the ctrl+click as an option (not implying your request is wrong, just curious).

**Comment by C-Pettersson** [comment]
The closest analogy I can think of would be "default apps" in your operating system. For this example the system default is chrome but you prefer Firefox. So instead of right clicking and select open in Firefox, you are allowed to change.

**Comment by wratho** [comment]
> The closest analogy I can think of would be "default apps" in your operating system. For this example the system default is chrome but you prefer Firefox. So instead of right clicking and select open in Firefox, you are allowed to change.

totally get that, but i believe the analogy breaks down in that both options are always one click away, just one required an additional key. I see value in this feature, and will investigate it at some point (been very busy)
