### ISSUE TITLE
Suggestion: Add version number/version date to poe-overlay

### ISSUE THREAD

**Issue by Gladaed** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#95]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

 I tried to check if poe-overlay is already the most current version, but can't. While autoupdate is technically on it would be nice to be able to check

**Describe the solution you'd like**

add info to the settings

**Describe alternatives you've considered**

on launch display a image stating basic information about the program

**Additional context**

Legacy software did struggle with updates, so there is distrust

ps: the template should state edit below. My text was commented out.

**Comment by HankTheDrunk** [comment]
It's in the bottom left corner when you bring the game into focus
![corner](https://user-images.githubusercontent.com/7755620/85866806-f95f3d80-b795-11ea-8d4a-8f8d320d1942.png)

**Comment by alsmith823** [comment]
This is already implemented as @HankTheDrunk mentioned. Closing
