### ISSUE TITLE
Parse error for indigo oils

### ISSUE THREAD

**Issue by donq123** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#96]
Version: 0.7.1
New oil for league is unable to be price checked.

**Comment by WhiteFang5** [comment]
This will be fixed in the next release (0.7.2 or later)

**Comment by livejamie** [comment]
Same for new gems I assume, getting an error on Intimidating Cry

**Comment by WhiteFang5** [comment]
> Same for new gems I assume, getting an error on Intimidating Cry

Yes, same thing. Seeds will also be supported to evaluate. Along with older content now also being properly searchable such as cluster jewels, metamorph samples and delirium orbs.

**Comment by livejamie** [comment]
Is this ready for testing? Making it really frustrating to use the tool.

**Comment by WhiteFang5** [comment]
This issue has been fixed with the release of 0.7.2
